version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR . . .
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 657728996878.ecr.$AWS_DEFAULT_REGION.amazonaws.com 
  build:
    commands:
      - java -version
      - mvn clean -Dmaven.test.skip=true package
      - docker-compose --file=docker-compose-prod.yml build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image... 
      - docker-compose --file=docker-compose-prod.yml push
    
artifacts:
  files:
    - 'Dockerrun.aws.json'
