version: 0.2

phases:
  build:
    commands:
      - java -version
      - mvn clean -Dmaven.test.skip=true package
      - docker-compose up -d 
artifacts:
  files:
    - 'Dockerfile'
    - target/e-commerce-0.0.1-SNAPSHOT.jar
