version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - java -version
      - mvn clean -Dmaven.test.skip=true package
      - docker-compose --file=docker-compose-prod.yml build
  post_build: 
    - echo Build completed on `date`
    - echo Pushing the Docker image... 
    - docker-compose --file=docker-compose-prod.yml push
artifacts:
  files:
    - 'Dockerrun.aws.json'
