server:
  port: 5000
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  h2:
    console.enabled: true
  sql:
    init:
      platform: postgres

