server:
  port: 5000
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://postgres.clbbpo0zoa9k.us-west-2.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ui1RY0nWFAzwRkWwmZKS
  h2:
    console.enabled: true
  sql:
    init:
      platform: postgres

